# Generated by Django 4.2.29 on 2026-04-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklylog',
            old_name='content',
            new_name='activities_done',
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='plan_for_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='skills_gained',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_students', to='core.academicsupervisorprofile'),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_students', to='core.workplacesupervisorprofile'),
        ),
    ]
