# Generated by Django 4.2.28 on 2026-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
