# Generated by Django 4.2.29 on 2026-05-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        ('core', '0002_remove_studentprofile_phone_number_and_more'),
    ]

    operations = [
    ]
