# Generated by Django 4.2.29 on 2026-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklylog_submitted_at_alter_weeklylog_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
