# Generated by Django 4.2.29 on 2026-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_internshipplacement_student'),
        ('core', '0002_evaluation_grade_evaluation_status_and_more'),
    ]

    operations = [
    ]
