# Generated by Django 4.2.29 on 2026-04-11 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evaluationcriteria_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('academic_supervisor', 'Academic Supervisor'), ('workplace_supervisor', 'Workplace Supervisor'), ('admin', 'Admin')], default='student', max_length=30),
        ),
    ]
