# Generated by Django 4.2.29 on 2026-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_content_weeklylog_activities_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
