# Generated by Django 6.0.5 on 2026-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260513_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
