# Generated by Django 4.2.29 on 2026-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260507_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='activity_done',
        ),
        migrations.RemoveField(
            model_name='weeklylog',
            name='plan_of_action',
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='skills_gained',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='strengths',
            field=models.TextField(blank=True, default=''),
        ),
    ]
