# Generated by Django 4.2.29 on 2026-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_weeklylog_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='week_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.CheckConstraint(
                condition=models.Q(week_number__gte=1) & models.Q(week_number__lte=52),
                name='week_number_valid_range'
            )
        )
    ]     
                condition=models.Q(week_number__gte=1) & models.Q(week_number__lte=52), 
                name='week_number_valid_range'),
        ),
    ]

