# Generated by Django 6.0.3 on 2026-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_department_customuser_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
