# Generated by Django 6.0.5 on 2026-05-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evaluation_unique_together_and_more'),
        ('core', '0004_alter_academicsupervisorprofile_staff_id'),
    ]

    operations = [
    ]
