# Generated by Django 6.0.3 on 2026-05-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentprofile_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
