# Generated by Django 4.2.29 on 2026-04-21 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_weeklylog_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
