# Generated by Django 4.2.29 on 2026-05-26 14:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260523_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='department',
            field=models.CharField(blank=True, default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='office_number',
            field=models.CharField(blank=True, default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workplacesupervisorprofile',
            name='company_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplacesupervisorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='workplacesupervisorprofile',
            name='position',
            field=models.CharField(blank=True, default='staff', max_length=100),
            preserve_default=False,
        ),
    ]
