# Generated by Django 6.0.3 on 2026-04-22 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_weeklylog_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        #migrations.AlterField(
            #model_name='evaluation',
            #name='score',
            #field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        #),
        migrations.AlterField(
            model_name='internshipplacement',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
