# Generated by Django 4.2.29 on 2026-05-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_weeklylog_activity_done_and_more'),
        ('core', '0005_alter_studentprofile_registration_number'),
    ]

    operations = [
    ]
