# Generated by Django 6.0.5 on 2026-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplacesupervisorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
