# Generated by Django 4.2.29 on 2026-04-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weeklyloghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='activity_done',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='plan_of_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='skills_gained',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
