# Generated by Django 4.2.29 on 2026-05-07 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260508_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='plan_for_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='skills_gained',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
