# Generated by Django 4.2.29 on 2026-05-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_weeklylog_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
