# Generated by Django 6.0.5 on 2026-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workplacesupervisorprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicsupervisorprofile',
            name='office_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workplacesupervisorprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
