# Generated by Django 4.2.29 on 2026-04-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evaluation_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='content',
        ),
    ]
