# Generated by Django 6.0.5 on 2026-06-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_academicsupervisorprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
