# Generated by Django 6.0.3 on 2026-04-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentprofile_phone_number_and_more'),
        ('core', '0010_alter_customuser_managers_evaluation_weekly_log'),
    ]

    operations = [
    ]
